.TH OPENFETCH 1 "July 2024" "OpenFetch 1.0"
.SH NAME
openfetch \- display system information

.SH SYNOPSIS
.B openfetch
.RI [ \-h | \-v ]

.SH DESCRIPTION
.B openfetch
is a simple tool to display information about a running FreeBSD, OpenBSD, NetBSD, or DragonFly BSD system.

.SH OPTIONS
.TP
.B \-h
Show help text.
.TP
.B \-v
Show version information.

.SH AUTHORS
Brian Callahan
.RI (bcallah@openbsd.org)
jhx
.RI (jhx0x00@gmail.com)
David Uhden Collado
.RI (david@uhden.dev)